apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world-servlet
  namespace: default
  labels:
    app: hello-world-servlet
    updateTimestamp: ${TIMESTAMP}
spec:
  selector:
    matchLabels:
      app: hello-world-servlet
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world-servlet
    spec:
      containers:
      - name: hello-world-servlet
        image: hello-world-servlet
        ports:
        - containerPort: 80
