apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hello-world-servlet
  namespace: ${target_environment}
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: disclosure
  maxReplicas: 5
  minReplicas: 3 
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 75