apiVersion: v1
kind: Service
metadata:
  name: hello-world-servlet
  labels:
    app: hello-world-servlet
  namespace: ${target_environment}
spec:
  type: NodePort
  selector:
    app: hello-world-servlet
  ports:
    -
      name: http
      port: 80
      targetPort: 8080